### ISSUE TITLE
I can't start minecraft at all with this mod

### ISSUE THREAD

**Issue by NeoGahme** [TangoTek/TekTopia-Community#1029]
I can't even start the game like it refuses to open. I mean, I can get onto the launcher, but I can't start it from there. This is the bug feed that I got back.

Time: 10/8/19 9:47 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TekTopia (tektopia)
Caused by: java.lang.NoClassDefFoundError: com/leviathanstudio/craftstudio/common/animation/AnimationHandler
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:393)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:576)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.leviathanstudio.craftstudio.common.animation.AnimationHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException

Please tell me if you need any more information and thank you for your time.

**Comment by semirotta** [comment]
How do you install the mod?
You are obviously doing something wrong.
Works fine through Twitch client though.

**Comment by NeoGahme** [comment]
I went to this link ( https://www.curseforge.com/minecraft/mc-mods/tektopia ) and clicked download, then I dragged it into my mods folder.

**Comment by JMAN0521** [comment]
I am having the same problem. same error and i cant find any answers either. Have you figured it out?

**Comment by smmmadden** [comment]
I had issues with downloading and only copying the file to the mods folder because the file contents do not have the right file structure (and it's a zip, not jar).  It wasn't packaged correctly for use without Twitch.

I recommend using Twitch to install it.  Once it is installed, the process will include the right format of the jar file which can then be used to copy/paste to a mods folder without having to use twitch. :-)

**Comment by JMAN0521** [comment]
How do i download it using twitch? I click install on the curse website and it just prompts to open twitch but doesnt do anything except open twitch, from what i can tell it doesnt actually install it

**Comment by smmmadden** [comment]
You could have googled for how to do this - but here you go.
Twitch is a Minecraft loader, so you have to have downloaded and installed it first.  
Twitch App: https://www.twitch.tv/downloads) 
Installation instructions on the wiki page https://sites.google.com/view/tektopia/home/about/twitch-installation

**Comment by iida-hayato** [comment]
I resolve this issue by adding
`mods/1.12.2/CraftStudio-1.0.0.93-mc1.12-alpha.jar`
in my server mods directory

**Comment by semirotta** [comment]
> I resolve this issue by adding
> `mods/1.12.2/CraftStudio-1.0.0.93-mc1.12-alpha.jar`
> in my server mods directory

3 Years.... This topic is 3 years old. You really, really really really thought it would be relevant still?

**Comment by NeoGahme** [comment]
Bruh, who are you
