### ISSUE TITLE
Resolved. I was using an old version of the mod. 

### ISSUE THREAD

**Issue by Enenica** [TangoTek/TekTopia-Community#704]
Just as a prequel, I'm running this on 1.12.2, single player, creative, with JEI 

I just started playing, I found a village that was pretty populated. I made a storage room, but now when a guard opens a chest the game crashes entirely.  It was at night as well. 

I've got the bug report, if that would help at all? 

To reproduce, make a chest, put a bunch of diamond gear in it (Maybe at night?) 
Wait. 
Crash. 
Restart. 
Crash! 

Edit: I thought it was only guards. Apparently it's all villagers? 
If it's something on my end, will you tell me how to fix it please?

Here's the crash report, I don't know if it will help.

---- Minecraft Crash Report ----
// My bad.

Time: 7/14/19 6:01 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: javafx/util/Pair
	at net.tangotek.tektopia.entities.ai.EntityAIRetrieveFromStorage.pickUpItems(EntityAIRetrieveFromStorage.java:130)
	at net.tangotek.tektopia.entities.ai.EntityAIRetrieveFromStorage.func_75246_d(EntityAIRetrieveFromStorage.java:91)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:211)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:633)
	at net.tangotek.tektopia.entities.EntityGuard.func_70636_d(EntityGuard.java:239)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.tangotek.tektopia.entities.ai.EntityAIRetrieveFromStorage.pickUpItems(EntityAIRetrieveFromStorage.java:130)
	at net.tangotek.tektopia.entities.ai.EntityAIRetrieveFromStorage.func_75246_d(EntityAIRetrieveFromStorage.java:91)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:211)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:633)
	at net.tangotek.tektopia.entities.EntityGuard.func_70636_d(EntityGuard.java:239)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: tektopia:guard (net.tangotek.tektopia.entities.EntityGuard)
	Entity ID: 6654
	Entity Name: Jaelynn Aliyar
	Entity's Exact location: -368.28, 64.00, 897.47
	Entity's Block location: World: (-369,64,897), Chunk: (at 15,4,1 in -24,56; contains blocks -384,0,896 to -369,255,911), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: TekTopia test
	All players: 1 total; [EntityPlayerMP['Eneicia'/1607, l='TekTopia test', x=-368.75, y=64.00, z=899.12]]
	Chunk stats: ServerChunkCache: 426 Drop: 0
	Level seed: 4661164154165123858
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (252,64,248), Chunk: (at 12,4,8 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16705 game time, 16705 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 39609 (now: false), thunder time: 28027 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 430923856 bytes (410 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID             | Version      | Source                                | Signature                                |
	|:--------- |:-------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft      | 1.12.2       | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp            | 9.42         | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML            | 8.0.99.99    | forge-1.12.2-14.23.3.2655.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge          | 14.23.3.2655 | forge-1.12.2-14.23.3.2655.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | craftstudioapi | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| UCHIJAAAA | jei            | 4.10.0.198   | jei_1.12.2-4.10.0.198.jar             | None                                     |
	| UCHIJAAAA | tektopia       | 1.0.11       | tektopia-1.0.11.jar                   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Eneicia'/1607, l='TekTopia test', x=-368.75, y=64.00, z=899.12]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Snodderz** [comment]
Are you on TekTopia version 1.0.11? First thing to do is check you have the latest version, currently 1.0.62

**Comment by Enenica** [comment]
I can check that, thank you.

**Comment by Enenica** [comment]
Testing it now. If it works, what do I do to close this?

**Comment by Snodderz** [comment]
Glad it worked. There's a close button on the add comment box below
