### ISSUE TITLE
CRASH - Barracks

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#725]
**Describe the bug**
I destroyed a bed in the barracks and the game crashed. Null Pointer Exception. Looks like it was scanning for a special block in the barracks which I can only assume is either the armor stand, or an inherited chair from the home.

**To Reproduce**
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.tangotek.tektopia.structures.VillageStructureHome.scanSpecialBlock(VillageStructureHome.java:78)
	at net.tangotek.tektopia.structures.VillageStructureBarracks.scanSpecialBlock(VillageStructureBarracks.java:35)
	at net.tangotek.tektopia.structures.VillageStructure.scanRoomHeight(VillageStructure.java:156)
	at net.tangotek.tektopia.structures.VillageStructure.scanFloor(VillageStructure.java:129)
	at net.tangotek.tektopia.structures.VillageStructure.scanFloor(VillageStructure.java:137)
	at net.tangotek.tektopia.structures.VillageStructure.doFloorScan(VillageStructure.java:120)
	at net.tangotek.tektopia.structures.VillageStructure.lambda$setupServerJobs$1(VillageStructure.java:87)
	at net.tangotek.tektopia.structures.VillageStructure$$Lambda$336/1441986145.run(Unknown Source)
	at net.tangotek.tektopia.tickjob.TickJob.tick(TickJob.java:31)
	at net.tangotek.tektopia.tickjob.TickJobQueue.tick(TickJobQueue.java:30)
	at net.tangotek.tektopia.structures.VillageStructure.update(VillageStructure.java:94)
	at net.tangotek.tektopia.structures.VillageStructureBarracks.update(VillageStructureBarracks.java:45)
	at net.tangotek.tektopia.Village.update(Village.java:868)
	at net.tangotek.tektopia.VillageManager.update(VillageManager.java:97)
	at net.tangotek.tektopia.TekVillager$RegistrationHandler.worldTick(TekVillager.java:168)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_RegistrationHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
**Expected behavior**

**Screenshots**

** Server/Location **
Single Player

**Additional context**
Version 1.0.68

**Comment by Snodderz** [comment]
I just got the same crash by doing the same thing. The same bed. Still a Null Pointer Exception on StructureHome.ScanSpecialBlock. After removing the token and replacing, it's stopped crashing when I destroy that particular bed.

**Comment by TangoTek** [comment]
I believe this was fixed right around the time this was reported.  Added a null check to the residents bedpos.  Let me know if this still occurs
