### ISSUE TITLE
CRASH - Guard in water

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#729]
**Describe the bug**
I was simply placing blocks and bam! Guard unhappy

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.tangotek.tektopia.entities.ai.EntityAIProtectVillage.func_75253_b(EntityAIProtectVillage.java:49)
	at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:83)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:885)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:282)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:729)
	at net.tangotek.tektopia.entities.EntityGuard.func_70636_d(EntityGuard.java:404)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

** Server/Location **
Single Player

**Additional context**
Version 1.0.71

**Comment by Snodderz** [comment]
When I logged back in I got the same crash again, pointing to the same line of code. So I checked them and it was actually x2 different Guards, first one was a "Diederich Kelmore" and the second was "Naj Daargen". When I got on a third time, it didn't crash, so I went looking for these two. I found them both - stuck in water. 

![image](https://user-images.githubusercontent.com/52452881/61579979-6d17b580-ab04-11e9-8c8a-23481f4d4f68.png)

**Comment by Snodderz** [comment]
Got the same crash a third time a few minutes later, again it was Diederich Kelmore (this guys becoming a pain) and found him in water again. PS - all three occasions occurred during the day. 

![image](https://user-images.githubusercontent.com/52452881/61580035-15c61500-ab05-11e9-8b8a-94417d39d43c.png)

**Comment by TangoTek** [comment]
Crash report was extremely helpful. Fixed in next patch. Thanks!
