### ISSUE TITLE
Fence Gate crash

### ISSUE THREAD

**Issue by UnholyFury92** [TangoTek/TekTopia-Community#769]
**Describe the bug**
When ranchers or butchers get caught in a fence gate and you can't move them out of it. You destroy the fence gate and your game crashes (Single player).

**To Reproduce**
See above

**Expected behavior**
Remove the fence gate to free the villagers

**Screenshots**

** Server/Location **
Single Player

**Additional context**
This has happened every time I've tried this method to free villagers from fence gates.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You're mean.

Time: 7/24/19 2:28 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=open, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.tangotek.tektopia.entities.ai.EntityAIOpenGate.toggleGate(EntityAIOpenGate.java:123)
	at net.tangotek.tektopia.entities.ai.EntityAIOpenGate.func_75251_c(EntityAIOpenGate.java:118)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:113)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:282)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:730)
	at net.tangotek.tektopia.entities.EntityRancher.func_70636_d(EntityRancher.java:99)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.tangotek.tektopia.entities.ai.EntityAIOpenGate.toggleGate(EntityAIOpenGate.java:123)
	at net.tangotek.tektopia.entities.ai.EntityAIOpenGate.func_75251_c(EntityAIOpenGate.java:118)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:113)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:282)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:730)
	at net.tangotek.tektopia.entities.EntityRancher.func_70636_d(EntityRancher.java:99)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: tektopia:rancher (net.tangotek.tektopia.entities.EntityRancher)
	Entity ID: 42180
	Entity Name: Ceirren Van Hyden
	Entity's Exact location: -430.50, 66.00, 444.70
	Entity's Block location: World: (-431,66,444), Chunk: (at 1,4,12 in -27,27; contains blocks -432,0,432 to -417,255,447), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['UnholyFury'/42361, l='New World', x=-432.14, y=65.94, z=443.76]]
	Chunk stats: ServerChunkCache: 1849 Drop: 0
	Level seed: 7270196760445191469
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-244,64,256), Chunk: (at 12,4,0 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4005882 game time, 5571571 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 45099 (now: false), thunder time: 79488 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 658313496 bytes (627 MB) / 1442840576 bytes (1376 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                                                 | Signature                                |
	|:------ |:-------------- |:------------ |:------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                                          | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                                          | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | craftstudioapi | 1.0.0        | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha (1).jar | None                                     |
	| LCHIJA | tektopia       | 1.0.75       | tektopia-1.0.75.jar                                    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['UnholyFury'/42361, l='New World', x=-432.14, y=65.94, z=443.76]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TangoTek** [comment]
Great catch. Thanks!  Fixed in next build
