### ISSUE TITLE
Second player clicking on merchant whilst first player is using him crashes game.

### ISSUE THREAD

**Issue by Shamshalabim** [TangoTek/TekTopia-Community#82]
**Describe the bug**
When going to access the merchant whilst Sober was using him, the game crashed out for me when I right-clicking on him. We tested it a second time and the result was the same.

**To Reproduce**
1. Find merchant
2. Right click on him when another player is accessing him.
3. My game crashes

**Expected behavior**
Either two player access to merchant, or no effect.

**Screenshots**
N/A

** Server/Location **
Main Server 1.
X: -3716, Y: 72, Z: 2019

**Additional context**
N/A

**Comment by IridescentShadow** [comment]
I experienced this issue as well, on SP opened to LAN. Here is the crash log:

```---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 5/26/19 8:28 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.tangotek.tektopia.gui.GuiVillager.func_146979_b(GuiVillager.java:69)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at net.tangotek.tektopia.gui.GuiVillager.func_73863_a(GuiVillager.java:44)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.tangotek.tektopia.gui.GuiVillager.func_146979_b(GuiVillager.java:69)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at net.tangotek.tektopia.gui.GuiVillager.func_73863_a(GuiVillager.java:44)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: net.tangotek.tektopia.gui.GuiVillager
	Mouse location: Scaled: (640, 344). Absolute: (1280, 689)
	Screen size: Scaled: (1280, 689). Absolute: (2560, 1378). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['IridescentShdow'/1155, l='MpServer', x=341.68, y=68.94, z=305.61], EntityOtherPlayerMP['alliek3'/869443, l='MpServer', x=339.64, y=68.94, z=306.29]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (224,64,256), Chunk: (at 0,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 371644 game time, 677166 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 183 total; [EntityBat['Bat'/974857, l='MpServer', x=283.46, y=29.31, z=303.98], EntityItemFrame['entity.ItemFrame.name'/768029, l='MpServer', x=320.50, y=72.50, z=323.03], EntityBat['Bat'/978978, l='MpServer', x=412.98, y=58.89, z=319.56], EntityBat['Bat'/979017, l='MpServer', x=388.72, y=23.65, z=384.18], EntityOtherPlayerMP['alliek3'/509481, l='MpServer', x=77.27, y=68.00, z=324.84], EntityBat['Bat'/979049, l='MpServer', x=268.75, y=19.00, z=383.75], EntitySkeleton['Skeleton'/974947, l='MpServer', x=388.50, y=24.00, z=271.50], EntityBat['Bat'/979060, l='MpServer', x=295.61, y=39.16, z=266.62], EntityOtherPlayerMP['alliek3'/509481, l='MpServer', x=312.83, y=71.00, z=575.07], EntitySheep['Sheep'/136, l='MpServer', x=263.19, y=70.00, z=338.59], EntitySheep['Sheep'/137, l='MpServer', x=300.27, y=71.00, z=380.50], EntitySheep['Sheep'/138, l='MpServer', x=274.26, y=67.00, z=364.45], EntitySheep['Sheep'/140, l='MpServer', x=270.45, y=69.00, z=381.24], EntitySheep['Sheep'/143, l='MpServer', x=272.23, y=67.00, z=368.33], EntityLumberjack['Dyrk Hartman'/177, l='MpServer', x=332.53, y=65.00, z=294.99], EntityFarmer['Naomi Rosemourne'/178, l='MpServer', x=312.20, y=68.94, z=313.44], EntityFarmer['Cassandra Daargen'/179, l='MpServer', x=315.53, y=70.42, z=326.30], EntityItemFrame['entity.ItemFrame.name'/184, l='MpServer', x=313.50, y=66.50, z=287.03], EntityFarmer['Nerle Faringray'/188, l='MpServer', x=304.69, y=67.94, z=315.23], EntityBlacksmith['Daniela Goldrudder'/189, l='MpServer', x=362.31, y=67.36, z=312.40], EntityFarmer['Sevenson Varzand'/190, l='MpServer', x=297.89, y=66.94, z=293.28], EntityFarmer['Dylan Fallenbridge'/191, l='MpServer', x=304.43, y=66.94, z=304.86], EntityLumberjack['Mia Strong'/192, l='MpServer', x=316.23, y=72.00, z=370.46], EntityLumberjack['Luciana Endless'/193, l='MpServer', x=355.11, y=65.00, z=283.11], EntityItemFrame['entity.ItemFrame.name'/618703, l='MpServer', x=311.50, y=67.50, z=289.97], EntitySheep['Sheep'/198, l='MpServer', x=262.11, y=69.00, z=312.38], EntityFarmer['Derek Coyle'/199, l='MpServer', x=313.50, y=68.94, z=314.66], EntityBlacksmith['Elaine Nando'/201, l='MpServer', x=358.72, y=68.00, z=297.70], EntityFarmer['Tamond Pyncion'/202, l='MpServer', x=313.50, y=69.23, z=315.22], EntityGuard['Kasaki Stormchapel'/218, l='MpServer', x=318.50, y=65.56, z=283.50], EntitySheep['Sheep'/219, l='MpServer', x=340.52, y=70.00, z=245.21], EntitySheep['Sheep'/220, l='MpServer', x=351.48, y=73.00, z=245.71], EntitySheep['Sheep'/222, l='MpServer', x=358.30, y=67.00, z=232.36], EntityFarmer['Madian Zethergyl'/226, l='MpServer', x=296.71, y=67.00, z=300.07], EntityFarmer['Sachil Silvergraft'/227, l='MpServer', x=296.83, y=67.00, z=295.71], EntityLumberjack['Shaun Hindergrass'/228, l='MpServer', x=290.30, y=72.00, z=315.50], EntityItemFrame['entity.ItemFrame.name'/229, l='MpServer', x=339.03, y=71.50, z=308.50], EntityItemFrame['entity.ItemFrame.name'/230, l='MpServer', x=341.97, y=70.50, z=296.50], EntityItemFrame['entity.ItemFrame.name'/232, l='MpServer', x=339.03, y=71.50, z=333.50], EntityItemFrame['entity.ItemFrame.name'/233, l='MpServer', x=341.97, y=71.50, z=330.50], EntityFarmer['Hew Van Devries'/234, l='MpServer', x=297.30, y=66.94, z=294.25], EntityLumberjack['Lavant Iscalon'/236, l='MpServer', x=335.77, y=65.00, z=293.61], EntityFarmer['Sariah Sell'/237, l='MpServer', x=347.48, y=67.17, z=290.71], EntityItemFrame['entity.ItemFrame.name'/238, l='MpServer', x=339.03, y=71.50, z=349.50], EntitySpider['Spider'/979168, l='MpServer', x=280.50, y=33.00, z=226.50], EntityItemFrame['entity.ItemFrame.name'/239, l='MpServer', x=341.97, y=71.50, z=347.50], EntitySheep['Sheep'/243, l='MpServer', x=348.45, y=70.00, z=311.94], EntitySheep['Sheep'/244, l='MpServer', x=348.95, y=70.00, z=312.92], EntityGuard['Anlow Hartman'/247, l='MpServer', x=347.22, y=67.00, z=291.45], EntityFarmer['Saidi Van Devries'/249, l='MpServer', x=369.43, y=65.05, z=290.62], EntityItemFrame['entity.ItemFrame.name'/250, l='MpServer', x=347.50, y=71.50, z=323.03], EntityItem['item.tile.sapling.oak'/979188, l='MpServer', x=386.83, y=83.00, z=328.96], EntityFarmer['Daniel Hindergrass'/251, l='MpServer', x=313.81, y=69.94, z=327.45], EntityBlacksmith['Gil Kerchas'/254, l='MpServer', x=354.38, y=69.00, z=315.16], EntitySheep['Sheep'/255, l='MpServer', x=394.38, y=74.00, z=368.79], EntityCreeper['Creeper'/979215, l='MpServer', x=282.48, y=19.00, z=305.80], EntityZombie['Zombie'/979203, l='MpServer', x=310.81, y=15.00, z=290.49], EntitySheep['Sheep'/269, l='MpServer', x=365.20, y=67.00, z=227.67], EntityItemFrame['entity.ItemFrame.name'/273, l='MpServer', x=364.97, y=68.50, z=308.50], EntityFarmer['Kasaki Kreel'/274, l='MpServer', x=296.97, y=66.94, z=299.23], EntityFarmer['Remora Shalabim'/276, l='MpServer', x=306.50, y=66.94, z=310.36], EntityCow['Cow'/285, l='MpServer', x=397.17, y=72.00, z=258.47], EntitySkeleton['Skeleton'/979216, l='MpServer', x=278.50, y=20.00, z=315.50], EntityCow['Cow'/286, l='MpServer', x=386.27, y=72.00, z=242.83], EntityCow['Cow'/287, l='MpServer', x=401.48, y=71.00, z=257.81], EntityCow['Cow'/288, l='MpServer', x=401.19, y=68.00, z=255.54], EntitySheep['Sheep'/290, l='MpServer', x=387.44, y=72.00, z=248.55], EntitySheep['Sheep'/291, l='MpServer', x=399.45, y=70.00, z=256.27], EntitySheep['Sheep'/292, l='MpServer', x=392.42, y=72.00, z=244.79], EntitySheep['Sheep'/293, l='MpServer', x=404.79, y=70.00, z=351.42], EntitySheep['Sheep'/294, l='MpServer', x=396.84, y=75.00, z=378.35], EntitySheep['Sheep'/295, l='MpServer', x=366.46, y=72.00, z=383.21], EntitySheep['Sheep'/296, l='MpServer', x=392.65, y=74.00, z=366.79], EntitySheep['Sheep'/298, l='MpServer', x=403.33, y=73.00, z=365.26], EntitySheep['Sheep'/299, l='MpServer', x=410.22, y=75.00, z=382.48], EntitySheep['Sheep'/300, l='MpServer', x=410.31, y=75.00, z=380.51], EntityHorse['Horse'/301, l='MpServer', x=382.56, y=71.00, z=352.37], EntityHorse['Horse'/302, l='MpServer', x=370.70, y=74.00, z=374.31], EntityCow['Cow'/307, l='MpServer', x=406.23, y=69.00, z=272.18], EntityCow['Cow'/308, l='MpServer', x=409.17, y=72.00, z=260.68], EntityCow['Cow'/309, l='MpServer', x=402.48, y=71.00, z=258.23], EntityCow['Cow'/310, l='MpServer', x=395.42, y=72.00, z=256.77], EntitySheep['Sheep'/311, l='MpServer', x=420.31, y=69.00, z=296.77], EntitySheep['Sheep'/313, l='MpServer', x=359.91, y=73.00, z=239.55], EntitySquid['Squid'/938292, l='MpServer', x=341.60, y=68.31, z=325.41], EntitySheep['Sheep'/314, l='MpServer', x=410.27, y=69.00, z=267.58], EntitySheep['Sheep'/328, l='MpServer', x=398.53, y=73.00, z=283.26], EntitySheep['Sheep'/329, l='MpServer', x=418.19, y=68.00, z=312.67], EntitySheep['Sheep'/330, l='MpServer', x=385.81, y=72.00, z=327.19], EntityItem['item.item.rottenFlesh'/969043, l='MpServer', x=367.69, y=70.00, z=339.13], EntityZombieVillager['Zombie Villager'/973153, l='MpServer', x=328.50, y=41.00, z=269.50], EntityChef['Megan Enotion'/162168, l='MpServer', x=332.80, y=70.00, z=315.67], EntityItem['item.tile.sapling.oak'/975218, l='MpServer', x=381.13, y=72.00, z=333.88], EntityBat['Bat'/979365, l='MpServer', x=335.32, y=39.09, z=266.42], EntitySkeleton['Skeleton'/977338, l='MpServer', x=332.50, y=26.00, z=287.50], EntityItem['item.item.apple'/975301, l='MpServer', x=382.88, y=72.00, z=332.88], EntityItemFrame['entity.ItemFrame.name'/532935, l='MpServer', x=359.50, y=69.50, z=304.03], EntityCreeper['Creeper'/979415, l='MpServer', x=285.50, y=15.00, z=300.50], EntityBat['Bat'/979436, l='MpServer', x=388.46, y=39.76, z=260.55], EntityOtherPlayerMP['alliek3'/184832, l='MpServer', x=125.09, y=79.00, z=291.74], EntityBat['Bat'/977411, l='MpServer', x=341.57, y=29.99, z=289.89], EntityItem['item.tile.sapling.oak'/979457, l='MpServer', x=382.45, y=83.00, z=327.97], EntityBat['Bat'/979516, l='MpServer', x=265.45, y=28.27, z=380.44], EntityBat['Bat'/979517, l='MpServer', x=267.50, y=26.73, z=382.75], EntityBat['Bat'/979515, l='MpServer', x=267.57, y=41.73, z=361.05], EntityItem['item.tile.sapling.oak'/979560, l='MpServer', x=384.88, y=73.00, z=308.61], EntityZombie['Zombie'/979556, l='MpServer', x=420.50, y=30.00, z=381.50], EntitySkeleton['Skeleton'/979568, l='MpServer', x=305.50, y=33.00, z=292.50], EntityItem['item.tile.sapling.oak'/975516, l='MpServer', x=348.19, y=65.00, z=283.67], EntityItemFrame['entity.ItemFrame.name'/967318, l='MpServer', x=305.50, y=13.50, z=369.03], EntityItem['item.tile.sapling.oak'/977577, l='MpServer', x=379.46, y=71.00, z=336.53], EntityOtherPlayerMP['alliek3'/125619, l='MpServer', x=183.46, y=66.00, z=250.57], EntityCreeper['Creeper'/979670, l='MpServer', x=407.50, y=27.00, z=353.89], EntityCreeper['Creeper'/979669, l='MpServer', x=407.50, y=27.00, z=354.59], EntityItemFrame['entity.ItemFrame.name'/543445, l='MpServer', x=364.97, y=67.50, z=298.50], EntitySkeleton['Skeleton'/979688, l='MpServer', x=270.50, y=36.00, z=285.50], EntityZombie['Zombie'/979687, l='MpServer', x=271.50, y=36.00, z=283.50], EntityMerchant['Leyten Van Devries'/971589, l='MpServer', x=339.62, y=68.94, z=304.92], EntityItem['item.tile.sapling.oak'/977790, l='MpServer', x=382.88, y=73.00, z=309.17], EntityMiner['Lavant Armanci'/961407, l='MpServer', x=324.21, y=17.00, z=369.44], EntityItemFrame['entity.ItemFrame.name'/529267, l='MpServer', x=360.50, y=70.50, z=327.97], EntitySpider['Spider'/979844, l='MpServer', x=291.50, y=39.00, z=266.50], EntitySkeleton['Skeleton'/979843, l='MpServer', x=295.50, y=39.00, z=267.50], EntityCreeper['Creeper'/979840, l='MpServer', x=397.50, y=41.00, z=263.50], EntityWitch['Witch'/977822, l='MpServer', x=304.50, y=33.00, z=292.50], EntityArchitect['Daylen Zethergyl'/5025, l='MpServer', x=334.50, y=70.00, z=348.50], EntityTradesman['Ace Seratolva'/5026, l='MpServer', x=336.60, y=70.00, z=348.30], EntityItem['item.tile.sapling.oak'/979881, l='MpServer', x=382.90, y=73.00, z=305.25], EntityBat['Bat'/979894, l='MpServer', x=274.27, y=25.32, z=253.27], EntityItemFrame['entity.ItemFrame.name'/766918, l='MpServer', x=304.03, y=68.50, z=310.50], EntityMiner['Anita Zethergyl'/504790, l='MpServer', x=332.78, y=65.56, z=297.26], EntityZombie['Zombie'/979926, l='MpServer', x=396.50, y=41.00, z=263.50], EntityCreeper['Creeper'/979927, l='MpServer', x=393.50, y=41.00, z=265.50], EntityZombie['Zombie'/979924, l='MpServer', x=395.50, y=41.00, z=264.50], EntityZombie['Zombie'/979925, l='MpServer', x=398.50, y=41.00, z=263.50], EntityOtherPlayerMP['alliek3'/509481, l='MpServer', x=73.64, y=69.00, z=318.17], EntityBat['Bat'/979956, l='MpServer', x=400.38, y=26.03, z=372.43], EntityBat['Bat'/979954, l='MpServer', x=409.25, y=26.08, z=368.52], EntityBat['Bat'/979955, l='MpServer', x=408.56, y=28.78, z=359.19], EntityOtherPlayerMP['alliek3'/869443, l='MpServer', x=339.64, y=68.94, z=306.29], EntityOtherPlayerMP['alliek3'/869443, l='MpServer', x=339.64, y=68.94, z=306.29], EntityCreeper['Creeper'/980057, l='MpServer', x=299.50, y=40.00, z=266.50], EntityOtherPlayerMP['alliek3'/349275, l='MpServer', x=301.39, y=70.14, z=107.55], EntityItem['item.tile.sapling.oak'/975972, l='MpServer', x=348.35, y=65.00, z=285.86], EntityZombie['Zombie'/978060, l='MpServer', x=408.51, y=45.00, z=244.81], EntitySpider['Spider'/978059, l='MpServer', x=396.87, y=37.00, z=253.14], EntityItemFrame['entity.ItemFrame.name'/46219, l='MpServer', x=327.97, y=66.50, z=295.50], EntityItem['item.tile.sapling.oak'/976044, l='MpServer', x=350.52, y=65.00, z=284.98], EntityItemFrame['entity.ItemFrame.name'/623781, l='MpServer', x=305.50, y=67.50, z=287.03], EntityZombie['Zombie'/980218, l='MpServer', x=292.50, y=38.00, z=262.50], EntitySkeleton['Skeleton'/980216, l='MpServer', x=292.50, y=38.00, z=261.50], EntityItemFrame['entity.ItemFrame.name'/720112, l='MpServer', x=370.50, y=70.50, z=327.97], EntitySkeleton['Skeleton'/980211, l='MpServer', x=350.50, y=28.00, z=331.50], EntityCreeper['Creeper'/980238, l='MpServer', x=419.50, y=22.00, z=382.50], EntitySpider['Spider'/980236, l='MpServer', x=416.65, y=22.00, z=380.70], EntitySpider['Spider'/980237, l='MpServer', x=418.50, y=22.00, z=385.50], EntityItemFrame['entity.ItemFrame.name'/965928, l='MpServer', x=308.50, y=13.50, z=371.97], EntityItemFrame['entity.ItemFrame.name'/873791, l='MpServer', x=322.50, y=72.50, z=325.97], EntityItemFrame['entity.ItemFrame.name'/965959, l='MpServer', x=308.50, y=13.50, z=369.03], EntityCreeper['Creeper'/980311, l='MpServer', x=358.50, y=41.00, z=361.50], EntityZombie['Zombie'/978280, l='MpServer', x=269.25, y=53.00, z=341.44], EntityOtherPlayerMP['alliek3'/320889, l='MpServer', x=308.71, y=66.00, z=296.09], EntityOtherPlayerMP['alliek3'/7423, l='MpServer', x=319.77, y=65.00, z=294.96], EntityOtherPlayerMP['alliek3'/52647, l='MpServer', x=315.58, y=65.00, z=299.26], EntityItem['item.tile.sapling.oak'/978360, l='MpServer', x=382.24, y=72.00, z=335.38], EntityBat['Bat'/978383, l='MpServer', x=340.30, y=26.13, z=332.91], EntityOtherPlayerMP['alliek3'/28198, l='MpServer', x=341.84, y=68.94, z=304.70], EntityItemFrame['entity.ItemFrame.name'/544319, l='MpServer', x=330.50, y=66.50, z=287.03], EntityBat['Bat'/978558, l='MpServer', x=413.75, y=26.02, z=368.75], EntityItemFrame['entity.ItemFrame.name'/616059, l='MpServer', x=321.50, y=66.50, z=287.03], EntityBat['Bat'/978556, l='MpServer', x=269.90, y=24.29, z=324.99], EntityBat['Bat'/978557, l='MpServer', x=407.75, y=27.10, z=366.75], EntityItem['item.tile.sapling.oak'/978590, l='MpServer', x=300.15, y=71.00, z=362.65], EntityItemFrame['entity.ItemFrame.name'/149148, l='MpServer', x=331.50, y=71.50, z=323.03], EntityItem['item.item.apple'/976619, l='MpServer', x=350.53, y=65.00, z=285.67], EntityPlayerSP['IridescentShdow'/1155, l='MpServer', x=341.68, y=68.94, z=305.61], EntityZombie['Zombie'/976636, l='MpServer', x=312.50, y=44.00, z=283.50], EntityOtherPlayerMP['alliek3'/253503, l='MpServer', x=349.63, y=71.00, z=358.43], EntityCreeper['Creeper'/978807, l='MpServer', x=388.50, y=24.00, z=382.50], EntitySkeleton['Skeleton'/978880, l='MpServer', x=417.50, y=61.00, z=326.16], EntitySkeleton['Skeleton'/978918, l='MpServer', x=411.50, y=43.00, z=270.50], EntityBat['Bat'/978938, l='MpServer', x=419.09, y=62.34, z=323.19], EntityMiner['Quentin Soberton'/960502, l='MpServer', x=305.49, y=11.00, z=366.73]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 858597432 bytes (818 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID             | Version      | Source                                | Signature                                |
	|:--------- |:-------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft      | 1.12.2       | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp            | 9.42         | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge          | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | craftstudioapi | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| UCHIJAAAA | tektopia       | 1.0.11       | tektopia-1.0.11.jar                   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/AKS.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz```

**Comment by JohnyDL** [comment]
Possibly related to #49

**Comment by TangoTek** [comment]
Fixed.  Thank you!
