### ISSUE TITLE
Trading at Merchant Crash

### ISSUE THREAD

**Issue by UnholyFury92** [TangoTek/TekTopia-Community#867]
**Describe the bug**
I was trading with the merchant and next thing I know the game crashes.

**To Reproduce**

**Expected behavior**

**Additional context**
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/30/19 5:34 PM
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach.teachAll(EntityAISchoolTeach.java:134)
	at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach.lambda$updateTask$2(EntityAISchoolTeach.java:118)
	at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach$$Lambda$638/536356382.run(Unknown Source)
	at net.tangotek.tektopia.tickjob.TickJob.tick(TickJob.java:31)
	at net.tangotek.tektopia.tickjob.TickJobQueue.tick(TickJobQueue.java:30)
	at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:309)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:796)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach.teachAll(EntityAISchoolTeach.java:134)
	at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach.lambda$updateTask$2(EntityAISchoolTeach.java:118)
	at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach$$Lambda$638/536356382.run(Unknown Source)
	at net.tangotek.tektopia.tickjob.TickJob.tick(TickJob.java:31)
	at net.tangotek.tektopia.tickjob.TickJobQueue.tick(TickJobQueue.java:30)
	at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:309)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:796)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: tektopia:teacher (net.tangotek.tektopia.entities.EntityTeacher)
	Entity ID: 28
	Entity Name: Cassandra Dojang
	Entity's Exact location: -501.32, 66.00, 403.23
	Entity's Block location: World: (-502,66,403), Chunk: (at 10,4,3 in -32,25; contains blocks -512,0,400 to -497,255,415), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['UnholyFury'/294, l='New World', x=-459.98, y=67.00, z=458.67]]
	Chunk stats: ServerChunkCache: 2401 Drop: 0
	Level seed: 7270196760445191469
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-244,64,256), Chunk: (at 12,4,0 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5545786 game time, 7275372 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 80474 (now: false), thunder time: 49501 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 913304640 bytes (870 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                                                 | Signature                                |
	|:------ |:-------------- |:------------ |:------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                                          | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                                          | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | craftstudioapi | 1.0.0        | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha (1).jar | None                                     |
	| LCHIJA | tektopia       | 1.0.87       | tektopia-1.0.87.jar                                    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['UnholyFury'/294, l='New World', x=-459.98, y=67.00, z=458.67]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by UnholyFury92** [comment]
Also I should mention that this crash was with the 1.0.87 version of Tektopia

**Comment by UnholyFury92** [comment]
After a couple more crashes later and reading those reports then coming back here and reading this one, its the school teach? I've removed my school and will keep updated on if I crash again.

**Comment by TangoTek** [comment]
Fixed in next build. Sorry about that.
